version: "3"
services:
  app:
    container_name: short
    restart: always
    build: .
    environment:
      - PORT=8080
    ports:
      - "8080:8080"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"