apiVersion: v1
kind: Service
metadata:
  name: short-service
spec:
  type: NodePort
  selector:
    appli: short
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001